config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'homepages#index'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :posts do
    resources :comments
    get 'page/:page', action: :index, on: :collection
  end

  mount Ckeditor::Engine => '/ckeditor'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :content, :link, presence: true

  validates :title, length: { maximum: 28 }
  validates :content, length: { maximum: 100 }

  has_many :comments, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  attr_accessor :login

  validates :username, presence: true, uniqueness: {case_sensitive: false}, format: { with: /\A[a-zA-Z0-9]+\Z/ }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable

  devise :omniauthable, omniauth_providers: [:facebook]

  has_many :articles, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  def self.find_first_by_auth_conditions(warden_conditions)

    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where("lower(username) = :value OR lower(email) = :value", value: login.downcase).first
    else
      where(conditions.to_hash).first
    end
  end

  def self.from_facebook(auth)
    where(facebook_id: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.username = auth.info.name
      user.image = auth.info.image
      user.password = Devise.friendly_token[0, 20]
      user.skip_confirmation!
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Permet de cacher la navbar sur la page d'accueil
  before_action :show_navbar

  protected

  def configure_permitted_parameters
    added_attrs = %i[username email password password_confirmation remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  def show_navbar
    @show_navbar = true
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_article, only: %i[show update edit destroy]

  def index
    @articles = Article.order('created_at DESC')
    @article = Article.new
  end

  def show; end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params.merge(user_id: current_user.id))
    if @article.save
      redirect_to articles_path, notice: "L'article a bien été créé."
    else
      render action: 'Nouveau article'
    end
  end

  def edit; end

  def update
    if @article.update_attributes(article_params)
      redirect_to articles_path, notice: "L'article a bien été mis à jour."
    else
      render action: 'edit'
    end
  end

  def destroy
    if @article.destroy
      redirect_to @article, notice: "L'article a bien été supprimé."
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end

  def find_article
    @article = Article.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:content))
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to post_path(@post)
    else
      flash.now[:danger] = "error"
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

end

app/controllers/homepages_controller.rb
# frozen_string_literal: true

class HomepagesController < ApplicationController
  # Permet de cacher la navbar sur la page d'accueil
  skip_before_action :show_navbar

  def index
    # Afficher les 4 derniers posts dans l'ordre chronologique
    @posts = Post.all.order('created_at DESC').first(4)
    @articles = Article.order('created_at DESC').first(2)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include Youtube

  before_action :authenticate_user!
  before_action :find_post, only: %i[show update edit destroy]

  def index
    @posts = Post.all.order("created_at DESC").page(params[:page]).per(12)
    @post = Post.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params.merge(user_id: current_user.id))

    parse_video_url(@post.link)
    @post.link = @results

    if @post.save
      flash[:notice] = "Musique partagée avec succès"
      redirect_to @post
    else
      flash[:alert] = "Il y a une petite erreur, merci de réessayer"
      render 'new'
    end
  end

  def show
      @random_post = Post.all.order(Arel.sql('random()')).limit(1)
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "La musique a bien été mis à jour."
    else
      flash[:alert] = "Il y a une petite erreur, merci de réessayer"
      render 'edit'
    end

  end

  def edit; end

  def destroy
    @post.destroy

    redirect_to posts_path, notice: 'Musique bien supprimée'
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :link)
  end

  def find_post
    @post = Post.find(params[:id])
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook

    @user = User.from_facebook(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentification
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session['devise.facebook'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/articles/_form.html.erb
<div class="container">
  <div class="column is-8 is-offset-2">
    <%= form_with(model: @article) do |f| %>
      <% if @article.errors.any? %>
        <ul>
          <%= @article.errors.full_messages.each do |message| %>
          <li><%= no comprende message %></li>
          <% end %>
        </ul>
      <% end %>
    <div class="field">
      <div class="control">
        <%= f.text_field :title, autofocus: true, class: "input is-primary is-large", placeholder: "Mets ton titre ici, poto !" %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.cktext_area :body, rows: 25 %>
      </div>
    </div>

    <div class="level">
      <div class="level-left">
        <%= f.submit "Partager mon article", class:"button is-primary" %>
      </div>
      <div class="level-right">
        <%= link_to fa_icon("undo", text:"Retour aux articles",class:"text-muted pull-left"), articles_path, class:"button" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<section class="section">
  <div class="title has-text-centered has-text-grey"> Editer l'article "<%="#{@article.title}" %>"</div>
  <%= render 'form' %>
</section>

app/views/articles/index.html.erb
<section id="articles-banner-index" class="hero is-warning is-bold">
  <div class="hero-body">
    <div class="container">
      <h1 class="title is-1 has-text-centered has-text-white">LES ARTICLES</h1>
    </div>
  </div>

  <div class="hero-foot">
    <nav class="tabs is-boxed is-fullwidth">
      <div class="container">
        <ul>
          <li><%= link_to fa_icon("eye", text:"Mes articles", class:"text-muted pull-left has-text-white"), root_path, class:"has-text-white" %></li></li>
          <li id="myBtn"><%= link_to fa_icon("plus-square", text:"Nouveau article", class:"text-muted pull-left has-text-white"), new_article_path, remote: true, class:"has-text-white"%></li>

          <!-- The Modal -->
          <div id="myModal" class="modal">
            <!-- Modal content -->
            <div class="modal-content">
              <span class="close">&times;</span>
              <%= render 'form' %>
            </div>
          </div>
        </ul>
      </div>
    </nav>
  </div>
</section>

<section class="section">
  <% @articles.each_slice(4) do |art| %>
    <div class="container">
      <% art.each do |article| %>
        <div class="box">
          <div class="tile is-ancestor is-centered">

            <div class="tile is-4">
              <figure class="image">
                <%= image_tag("https://via.placeholder.com/400x300") %>
              </figure>
            </div>

            <div class="tile">
              <article class="tile is-child">
                <div class="title">
                  <%= article.title.html_safe %>
                </div>
                <div class="content">
                  <%= article.body.truncate_words(20).html_safe %>
                </div>
              </article>
            </div>
            <div class="tile is-2 has-text-centered tile-footer">
              <p>Publié.e par
                <%= article.user.username.capitalize %>
              </p>
              <%= link_to fa_icon("plus", text:"Détails", class:"text-muted pull-left"), article_path(article), class:"button is-info" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</section>

app/views/articles/new.html.erb
<%= render "form" %>

app/views/articles/show.html.erb
<section class="articles">
  <div class="column is-10 is-offset-1">
    <!-- START ARTICLE -->
    <div class="card article">
      <div class="card-content">
        <div class="media">
          <div class="media-content has-text-centered">
            <p class="title article-title"><%= @article.title.html_safe %></p>
              <div class="tags has-addons level-item">
                <% if user_signed_in? && @article.user_id == current_user.id %>
                <%= link_to "Editer", edit_article_path(@article), class: "tag is-rounded"%>
                <%= link_to "Supprimer", article_path(@article), method: :delete, data: { confirm: "Are you sure ?"}, class:"tag is-rounded is-danger"%>
                <% end %>
              </div>
            </div>
        </div>
        <div class="content article-body">
          <%=@article.body.html_safe%>
        </div>
      </div>
    <footer class="card-footer">
      <p class="card-footer-item"><%= @article.user.username%></p>
      <p class="card-footer-item"><%= @article.created_at.strftime("Posté le %d/%m/%Y")%>
    </footer>
    </div>
    <!-- END ARTICLE -->
  </div>
</section>

app/views/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= comment.user.username.capitalize %> : </strong>
          <%= comment.content %>
        </p>
      </div>
    </div>

    <div class="buttons are-small">
      <% if user_signed_in? && comment.user_id == current_user.id %>
      <%= link_to fa_icon("bomb", text:"Supprimer", class:"text-muted pull-left"), [comment.post, comment], method: :delete, class: "button is-danger", data: {confirm: "Sûr ?" } %>
      <% else %>

      <% end %>

      <%= fa_icon "history", text: "#{comment.created_at.strftime("Posté le %d/%m/%Y")}",class: "text-muted pull-left" %>

    </div>
  </article>
</div>

app/views/comments/_form.html.erb
  <%= form_for([@post, @post.comments.build]) do |f| %>
    <article class="media">
      <figure class="media-left">
        <p class="image is-64x64">
          <% if user_signed_in? && current_user.image.blank? %>
              <%= image_tag("128x128.png") %>
          <% elsif user_signed_in? && current_user.image.present? %>
              <%= image_tag current_user.image + "?type=large"%>
          <% else %>
          <% end %>
        </p>
      </figure>

      <div class="media-content">
        <div class="field">
          <p class="control">
            <%= f.text_area :content, class: "textarea", placeholder:"Ajouter un commentaire..." %>
          </p>
        </div>

        <nav class="level">
          <div class="level-left">
            <div class="level-item">
              <%= f.submit "Publier", class:"button is-primary" %>
            </div>
          </div>
        </nav>
      </div>
    </article>
  <% end %>

app/views/homepages/_connectedindex.html.erb
<nav class="navbar is-gray" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to image_tag("logokyo.png", height: '100', width: '100', class: "navbar-item logo"), root_path %>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Accueil", root_path, class: "navbar-item fucking-list" %>

      <%= link_to "Musiques", posts_path, class: "navbar-item fucking-list" %>

      <%= link_to "Articles", articles_path, class: "navbar-item fucking-list" %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if user_signed_in? %>

            <div class="dropdown is-hoverable">
              <div class="dropdown-trigger">
                <%= link_to edit_user_registration_path, "aria-haspopup": true, "aria-controls": "dropdown-menu4" do %>
                  <div class="button">
                    <% if current_user.image.blank? %>
                    <% else %>
                      <%= image_tag current_user.image, class: "image is-32x32" %>
                    <%end%>
                    <%= current_user.username.capitalize %>
                  </div>
                <%end%>
                <div class="dropdown-menu" id="dropdown-menu4" role="menu">
                  <div class="dropdown-content">
                    <div class="dropdown-item">
                      <%= link_to "Mon compte", edit_user_registration_path, class: 'button is-light is-fullwidth' %>
                      <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "button is-danger is-fullwidth" %>
                    </div>
                  </div>
                </div>
              </div>
            </div>


          <% else %>
            <div class="dropdown is-hoverable">
              <div class="dropdown-trigger">
                <%= link_to fa_icon("connectdevelop", text:"Connexion", class:"text-muted pull-left"), new_user_session_path, class: 'button', "aria-haspopup": true, "aria-controls": "dropdown-menu4" %>
              </div>
              <div class="dropdown-menu" id="dropdown-menu4" role="menu">
                <div class="dropdown-content">
                  <div class="dropdown-item">
                    <%= link_to fa_icon("connectdevelop", text:"Connexion", class:"text-muted pull-left"), new_user_session_path, class: 'button is-light is-fullwidth' %>
                    <%= link_to user_facebook_omniauth_authorize_path, class:"button is-info is-fullwidth" do %>
                      <%= fa_icon "facebook-square 2x" , text: "Facebook", class: "text-muted pull-left"%>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            &nbsp;&nbsp;
            <%= link_to fa_icon("user-plus", text:"Inscription", class:"text-muted pull-left"), new_user_registration_path, class: 'button is-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>
<section id="connected-banner-index" class="hero is-medium is-primary is-bold">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">
        À la une
      </h1>
      <h2 class="subtitle">
        Les derniers ajouts
      </h2>
    </div>
  </div>
</section>

<section class="section">
  <div class="columns is-desktop">
<!-- DISPLAY LAST SHARED MUSIC -->
    <div class="column">
      <div class="box">
        <h2 class="title has-text-centered has-text-grey-dark"> Musiques </h2>

          <div class="level">
            <div class="level-left">
              <div class="level-item">
                <%= link_to "Toutes les musiques", posts_path, class:"button is-rounded"%>
              </div>
            </div>
            <div class="level-right">
              <div class="level-item">
                <%= link_to fa_icon("plus", text:"Partager une musique", class:"text-muted pull-left"), new_post_path, class:"button is-primary is-rounded"%>
              </div>
            </div>
          </div>

          <div class="column">
            <% @posts.each_slice(4) do |music| %>
            <div class="columns">
              <% music.each do |post| %>
              <div class="column is-one-quarter">
                <!-- CARD -->
                <div class="card bm--card-equal-height">

                  <div class="card-image">
                    <figure class="image is-4by3">
                      <%= image_tag("http://img.youtube.com/vi/#{post.link}/0.jpg") %>
                    </figure>
                  </div>

                  <div class="card-content">
                    <div class="media">
                      <div class="media-content has-text-centered">
                        <p class="title is-4 has-text-dark"><%= post.title %></p>
                        <p class="subtitle is-6 has-text-dark"> Publié(e) par <%= post.user.username.capitalize %></p>
                      </div>
                    </div>
                    <div class="content">
                      <%= post.content %>
                    </div>
                  </div>


                  <div class="card-footer">
                    <span class="card-footer-item"><%= post.comments.count %> Commentaire(s)</span>
                  </div>

                  <footer class="card-footer"><%= link_to fa_icon("eye", text:"Voir", class:"text-muted pull-left"), post_path(post), class:"button card-footer-item" %>

                </div>
                <!-- END CARD -->
              </div>
              <% end %>
            </div>
            <% end %>
        </div>

        <div class="container is-fluid has-text-centered">
            <%= link_to fa_icon("plus", text:"Voir plus", class:"text-muted pull-left"), posts_path, class:"button is-primary is-rounded" %>
        </div>

      </div>
    </div>
<!-- END SHARED MUSIC -->
<!-- SECTION WITH THE LAST ARTICLES-->
      <div class="column is-one-quarter-fullhd">
        <div class="box">
          <h2 class="title has-text-centered has-text-grey-dark"> Articles </h2>
          <div class="level">
            <div class="level-left">
              <div class="level-item">
              </div>
            </div>
            <div class="level-right">
              <div class="level-item">
                <%= link_to fa_icon("pencil", text:"Ecrire un article", class:"text-muted pull-left"), new_article_path, class:"button is-primary is-rounded"%>
              </div>
            </div>
          </div>

          <% @articles.each do |article| %>
          <div class="box">
            <article class="media">
              <div class="media-left">
                <figure class="image is-64x64">
                  <% if current_user.image.blank? %>
                  <img src="https://versions.bulma.io/0.7.0/images/placeholders/128x128.png" alt="Image">
                  <% else %>
                      <%= image_tag current_user.image %>
                  <%end%>
                </figure>
              </div>
              <div class="media-content">
                <div class="content">
                  <p>
                    <strong><%= article.user.username.capitalize %></strong> <small>@<%= article.title.html_safe %></small>
                    <br>
                    <%= article.body.truncate_words(20).html_safe %>
                  </p>
                </div>
              </div>
            </article>
            <%= link_to fa_icon("eye", text:"Voir", class:"text-muted pull-left"), article_path(article), class:"button card-footer-item" %>
          </div>
          <% end %>
          <div class="container is-fluid has-text-centered">
            <%= link_to fa_icon("plus", text:"Voir plus", class:"text-muted pull-left"), articles_path, class:"button is-primary is-rounded" %>
          </div>
        </div>
      </div>
<!-- END ARTICLES SECTION -->
  </div>
</section>

app/views/homepages/index.html.erb
<% if user_signed_in? %>


  <%= render "homepages/connectedindex" %>

<% else %>

  <section id="kyodai-landing"class="hero is-fullheight">
    <!-- Hero content: will be in the middle -->
    <div class="hero-body">
      <div class="container has-text-centered">
        <figure class="avatar animated slideInDown">
          <%= image_tag("favicon.png", height: '100', width: '100')%>
        </figure>

        <div class="title has-text-white animated slideInDown">
          KYÔDAÏ
        </div>

        <div class="subtitle has-text-white animated slideInUp">
          Bienvenue<br>
          Venez découvrir ou partager des articles et des musiques !
        </div>

        <div class="column is-8 is-offset-2">
          <div class="level animated slideInUp">
            <div class="level-item">
              <%= link_to fa_icon("connectdevelop", text:"Connexion", class:"text-muted pull-left"), new_user_session_path, class: 'button is-rounded is-medium' %>
            </div>
            <div class="level-item">
              <%= link_to fa_icon("user-plus", text:"Inscription", class:"text-muted pull-left"), new_user_registration_path, class: 'button is-rounded is-primary is-medium' %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="hero-foot">
      <div class="container">
        <div class="mouse-container animated lightSpeedIn">
          <a class="js-scrollTo" href="#page-2">
            <span class="mouse-outer">
              <span class="mouse-wheel"></span>
            </span>
          </a>
        </div>
      </div>
    </div>

  </section>

  <section id="page-2" class="hero is-fullheight">
    <div class="hero-body">
      <div class="container has-text-centered has-text-white">

        <div class="tile is-ancestor">
          <div class="tile is-4 is-vertical is-parent">
            <div class="tile is-child">
              <figure class="avatar">
                <%= image_tag("logokyo.png", height: '150', width: '150')%>
              </figure>
            </div>
          </div>

          <div class="tile is-parent">
            <div class="tile is-child">
              <p class="title has-text-white">KYÔDAÏ, qu’est-ce que c’est ?</p>
              <p>Du japonais 兄弟, qui veut dire frères et soeurs. C'est avant tout une plateforme fait par un groupe d'amis pour le groupe d'amis.</p>
              <p>Sur ce site vous pourrez partager, mais aussi découvrir des articles et des musiques provenant de la plateforme YouTube.</p>
            </div>
          </div>
        </div>

        <div class="tile is-ancestor">
          <div class="tile is-parent">
            <div class="tile is-child">
              <p class="title has-text-white">L'Oniboso Crew</p>
              <p>Groupe formé en 2002 par 6 membres.</p>
              <p>Avant tout un groupe de danseurs hip-hop, mais aussi de monteur vidéo, monteur son et d'un caméraman.</p>
            </div>
          </div>

          <div class="tile is-parent is-4 is-vertical">
            <div class="tile is-child">
              <figure class="avatar">
                <%= image_tag("onibosologo.png", height: '150', width: '150')%>
              </figure>
            </div>
          </div>
        </div>

      </div>
    </div>
  </section>

<% end %>

app/views/posts/edit.html.erb
<section class="section">
  <div class="title has-text-centered has-text-grey"> Editer</div>
  <%= render 'form' %>
</section>

app/views/posts/index.html.erb
<section id="posts-banner-index" class="hero is-medium is-warning is-bold">
  <div class="hero-body">
    <div class="container">
      <h1 class="title is-1 has-text-centered has-text-white">LES MUSIQUES</h1>
    </div>
  </div>

  <div class="hero-foot">
    <nav class="tabs is-boxed is-fullwidth">
      <div class="container">
        <ul>
          <li><%= link_to fa_icon("eye", text:"Mes musiques", class:"text-muted pull-left has-text-white"), root_path, class: "has-text-white" %></li>
          <li id="myBtn"><%= link_to fa_icon("plus-square", text:"Nouvelle musique", class:"text-muted pull-left has-text-white"), new_post_path, remote: true, class:"has-text-white" %></li>

          <!-- The Modal -->
          <div id="myModal" class="modal">
            <!-- Modal content -->
            <div class="modal-content">
              <span class="close">&times;</span>
              <%= render 'form' %>
            </div>
          </div>

        </ul>
      </div>
    </nav>
  </div>
</section>

<section class="section">
  <div class="container">
    <% @posts.each_slice(4) do |music| %>
    <div class="columns">
      <% music.each do |post| %>
      <div class="column is-one-quarter">
        <div class="card bm--card-equal-height">

          <div class="card-image">
            <figure class="image is-4by3">
              <%= image_tag("http://img.youtube.com/vi/#{post.link}/0.jpg") %>
            </figure>
          </div>

          <div class="card-content">
            <div class="media">
              <div class="media-content has-text-centered">
                <p class="title is-4"><%= post.title %></p>
              </div>
            </div>

            <div class="content">
              <%= post.content %>
            </div>

          </div>

          <div class="card-footer">
            <span class="card-footer-item"><%= post.comments.count %> Commentaire(s)</span>
            <p class="card-footer-item">Publié(e) par <%= post.user.username.capitalize %></p>
          </div>

          <footer class="card-footer">
            <%= link_to fa_icon("plus", text:"Détails", class:"text-muted pull-left"), post_path(post), class:"card-footer-item button is-info" %>
          </footer>

        </div>
      </div>
      <% end %>
    </div>
    <% end %>
    <%= paginate @posts, outer_window: 2 %>
  </div>
</section>

app/views/posts/show.html.erb
<section class="hero is-primary is-bold">
  <div class="hero-body has-text-centered">
    <h1 class="title"><%= @post.title %></h1>
    <div class="columns">
<!-- Colonne de droite -->
      <div class="column is-two-thirds">
        <iframe id="ytplayer" type="text/html" width="640" height="360" src="https://www.youtube.com/embed/<%=@post.link%>?autoplay=0" frameborder="0">
        </iframe>

        <div class="section">
          <%= @post.content %>
        </div>
        <% if user_signed_in? && @post.user_id == current_user.id %>
          <%= link_to "Editer", edit_post_path(@post), class:"button" %>
          <%= link_to "Supprimer", post_path(@post), method: :delete, data: { confirm: "Are you sure ?"}, class:"button is-danger" %>
        <% end %>
      </div>
<!-- FIN COLONNE DE DROITE -->
<!-- Colonne de gauche -->
      <div class="column">
        <h2 class="subtitle"> Une autre au hasard ? </h2>
        <% @random_post.each do |rand| %>
          <iframe id="ytplayer" type="text/html" src="https://www.youtube.com/embed/<%= rand.link%>?autoplay=0" frameborder="0">
          </iframe>
        <% end %>

      </div>
<!-- FIN COLONNE DE GAUCHE -->
    </div>
  </div>
</section>


<section class="section comments">
  <div class="container">
    <h2 class="subtitle is-5"><strong class="button is-rounded"><%= @post.comments.count %> Commentaires</strong></h2>
    <%= render @post.comments %>
    <div class="comment-form">
      <hr />
      <h3 class="subtitle is-4">Laisse ton avis</h3>
      <%= render "comments/form" %>
    </div>
  </div>
</section>